name: CI

on:
  push:
    branches:
      - "**"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: lint
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest &&
          $HOME/go/bin/staticcheck &&
          make vet

  build:
     runs-on: ubuntu-latest
     strategy:
       matrix:
         go:
           - "1.20"
           - "1.19"
           - "1.18"
           - "1.17"
           - "1.16"
     name: "Build: go v${{ matrix.go }}"
     steps:
       - uses: actions/checkout@v2
       - name: Setup go
         uses: actions/setup-go@v1
         with:
           go-version: ${{ matrix.go }}
       - name: Build
         run: make build-example
